version: '3.3'

services:
    rabbit:
        build: ./rabbit-mqtt
        ports:
            - "15672:15672"
            - "5672:5672"
            - "1883:1883"
        volumes:
            - /tmp/docker/rabbit:/tmp/docker/rabbit
    prepros:
        build: ./pre-processor
        links:
            - rabbit
        environment:
            - BROKER_ADDRESS=rabbit
