version: '3.3'

services:
    rabbit:
        build: ./rabbit-mqtt
        ports:
            - "15672:15672"
            - "5672:5672"
            - "1883:1883"
        volumes:
            - /tmp/docker/rabbit:/tmp/docker/rabbit
    mongo:
        build: mongodb:latest
        ports:
            - "27017:27017"
    redis:
        build: redis:latest
        ports:
            - "6379:6379"
    router:
        build: ./wyze-router
        links:
            - rabbit
            - mongo
            - redis
        environment:
            - BROKER_ADDRESS=rabbit
            - MONGO_URL=mongodb://mongo:27017/wyze
            - REDIS_ADDRESS=redis
    engine:
        build: ./wyze-engine
        links:
            - rabbit
            - mongo
            - redis
        environment:
            - BROKER_ADDRESS=rabbit
            - MONGO_URL=mongodb://mongo:27017/wyze
            - REDIS_ADDRESS=redis
    console:
        build: ./mgnt-console
        links:
            - rabbit
            - mongo
            - redis
        environment:
            - BROKER_ADDRESS=rabbit
            - MONGO_URL=mongodb://mongo:27017/wyze
            - REDIS_ADDRESS=redis
        ports:
            - "5000:5000"